### ISSUE TITLE
Why the ServerAcceptor.java used accept() instead of selector?

### ISSUE THREAD

**Issue by xie233** [jjenkov/java-nio-server#12]

**Comment by jjenkov** [comment]
It only makes sense to use a Selector if you need to manage more than one socket. The ServerAcceptor only manages a single ServerSocket, so using a Selector is unnecessary.

**Comment by leexuehan** [comment]
I have read all your tutorials about NIO. It is really really good and benefits me a lot. Looking forward to reading your new articles.

**Comment by jjenkov** [comment]
Thanks :-)
